const fs = require('fs'); 
const dotenv = require('dotenv'); 
const { getDbPromise, getCollectionPromise } = require('../dist/library/db')

dotenv.config(); 
let { PORT, DB_NAME, dbUn, dbPass } = process.env; 





(async function(){

    const teamNames = loadTeamNames();
    const docs = teamNames.map(name => {
        return {
            name: name,
            type: "team"
        }
    })
    const writeResult = await writeDocs('simulation-fantasy-name-suggestions', docs); 
    console.log('write result: ', writeResult); 
})()






async function getCollection(collectionName){
    const dbConnectionStr =
        `mongodb+srv://${dbUn}:${dbPass}@nysdrillteams.4t9radi.mongodb.net/?retryWrites=true&w=majority`;
    const dbPromise = await getDbPromise(dbConnectionStr, DB_NAME);
    const collection = await getCollectionPromise(dbPromise, collectionName); 
    return collection; 
}

async function writeDocs(collectionName, documents){
    let collection = await getCollection(`${collectionName}`); 
    let result; 
    try {
        console.log('starting write to db: '); 
        result = await collection.insertMany(documents)
        console.log('write to db finished.  result: ', result); 
    } catch(e) {
        console.log('error during db write: ', e); 
    }
    return result; 
}

function loadTeamNames() {
    return [        
    "Aftershock",
    "Alley Cats",
    "Ambassadors",
    "Anvils",
    "Apollos",
    "Arsonists",
    "Assailants",
    "Avalanche",
    "Axes",
    "Aviators",
    "Backdraft",
    "Badgers",
    "Bandits",
    "Barnburners",
    "Barracudas",
    "Battalion",
    "Beacons",
    "Berserkers",
    "Blaze",
    "Blitz",
    "Blockbusters",
    "Bluecoats",
    "Bolts",
    "Boomers",
    "Boosters",
    "Brassmen",
    "Breakers",
    "Broncos",
    "Bruisers",
    "Buccaneers",
    "Cannons",
    "Captains",
    "Cavaliers",
    "Chargers",
    "Chasers",
    "Chieftains",
    "Chimeras",
    "Clutch",
    "Coalmen",
    "Commandos",
    "Comets",
    "Cougars",
    "Crusaders",
    "Cyclones",
    "Daredevils",
    "Defenders",
    "Demons",
    "Destroyers",
    "Detonators",
    "Devils",
    "Disruptors",
    "Divers",
    "Dodgers",
    "Dragons",
    "Drillers",
    "Dynamos",
    "Eagles",
    "Elites",
    "Embers",
    "Enforcers",
    "Engines",
    "Escalators",
    "Explorers",
    "Falcons",
    "Flares",
    "Flashpoint",
    "Flames",
    "Flyers",
    "Forgers",
    "Foxes",
    "Furies",
    "Gales",
    "Gangbusters",
    "Gasmen",
    "Generators",
    "Gladiators",
    "Go-Getters",
    "Grinders",
    "Guardians",
    "Gunners",
    "Hammers",
    "Hardhats",
    "Hawks",
    "Heatseekers",
    "Hellraisers",
    "Hose Hounds",
    "Hotshots",
    "Hurricanes",
    "Hydrants",
    "Hyperions",
    "Igniters",
    "Impalers",
    "Imps",
    "Infernos",
    "Ironmen",
    "Jets",
    "Juggernauts",
    "Jumpers",
    "Knights",
    "Krushers",
    "Lancers",
    "Lasers",
    "Leapers",
    "Legion",
    "Lifeliners",
    "Lightning",
    "Loaders",
    "Locomotives",
    "Longshots",
    "Lugnuts",
    "Machinists",
    "Marauders",
    "Mariners",
    "Mavericks",
    "Mechanix",
    "Mercenaries",
    "Metalmen",
    "Miners",
    "Monsoons",
    "Monarchs",
    "Motormen",
    "Mustangs",
    "Nightcrawlers",
    "Nightshift",
    "Nomads",
    "Nova",
    "Oilers",
    "Outlaws",
    "Overdrive",
    "Oxen",
    "Pacers",
    "Panthers",
    "Paramedics",
    "Patrollers",
    "Phantoms",
    "Phoenix",
    "Pioneers",
    "Pit Crew",
    "Pistons",
    "Platoon",
    "Powerhouse",
    "Predators",
    "Pressure",
    "Protectors",
    "Pulse",
    "Pyros",
    "Quakers",
    "Quickstep",
    "Quicksilvers",
    "Racers",
    "Rangers",
    "Rapid Response",
    "Ravagers",
    "Reapers",
    "Rebels",
    "Redline",
    "Rescue",
    "Responders",
    "Rockets",
    "Rogues",
    "Roughnecks",
    "Sabers",
    "Scorchers",
    "Scouts",
    "Scramblers",
    "Sentinels",
    "Shockwave",
    "Sizzlers",
    "Smokestacks",
    "Smolders",
    "Snappers",
    "Solars",
    "Sparkplugs",
    "Speedsters",
    "Spitfires",
    "Sprinters",
    "Squadron",
    "Steamers",
    "Steelmen",
    "Stormchasers",
    "Strikers",
    "Sultans",
    "Supersonics",
    "Surge",
    "Swelters",
    "Switchblades",
    "Tacticians",
    "Tankers",
    "Team Torque",
    "Tempests",
    "Thunderbolts",
    "Tigers",
    "Torchbearers",
    "Trailblazers",
    "Transports",
    "Trigger Men",
    "Troopers",
    "Turbines",
    "Turnout",
    "Typhoons",
    "Undertakers",
    "Unit 5",
    "Upstarts",
    "Valkyries",
    "Vanguard",
    "Vapor",
    "Venturers",
    "Veterans",
    "Vigilantes",
    "Voltage",
    "Voyagers",
    "Wagonmen",
    "Warriors",
    "Watchmen",
    "Welders",
    "Whirlwinds",
    "Wildcards",
    "Wolfpack",
    "Workhorses",
    "Wranglers",
    "X-Factor",
    "Xcelerators",
    "Xenons",
    "Yarddogs",
    "Yellowjackets",
    "Youngbloods",
    "Zealots",
    "Zephyrs",
    "Zeros",
    "Zodiacs",
    "Division Commanders",
    "Squad Chargers",
    "Core Vultures",
    "Shift Bulls",
    "Volt Rescuers",
    "Drill Wolves",
    "Zone Hosemen",
    "Flash Hosemen",
    "Rapid Jets",
    "Thunder Hosemen",
    "Zone Bulls",
    "Rapid Bombers",
    "Flare Raiders",
    "Vector Rockets",
    "Surge Bulls",
    "Bravo Flyers",
    "Shift Warriors",
    "Rift Wolves",
    "Volt Runners",
    "Edge Strikers",
    "Force Infernos",
    "Torch Flashers",
    "Volt Racers",
    "Pressure Ironmen",
    "Squad Breakers",
    "Flash Guardians",
    "Flash Blazers",
    "Company Outlaws",
    "Fire Grinders",
    "Spark Firebirds",
    "Inferno Hawks",
    "Core Scorchers",
    "Volt Ironmen",
    "Flash Cats",
    "Delta Titans",
    "Crew Wolves",
    "Blaze Reapers",
    "Iron Rescuers",
    "Iron Gunners",
    "Torch Wolves",
    "Inferno Grinders",
    "Flint Cats",
    "Ash Strikers",
    "Inferno Trackers",
    "Front Falcons",
    "Band Vikings",
    "Smoke Ironmen",
    "Vector Chargers",
    "Squad Bulls",
    "Turbo Hounds",
    "Grit Foxes",
    "Vector Hounds",
    "Bravo Warriors",
    "Band Mechanics",
    "Squad Blazers",
    "Gear Trackers",
    "Steel Blitz",
    "Steam Marauders",
    "Force Trackers",
    "Engine Raiders",
    "Thunder Chargers",
    "Inferno Sprinters",
    "Rush Cobras",
    "Tempest Vikings",
    "Flint Vultures",
    "Power Flashers",
    "Crew Strikers",
    "Iron Mechanics",
    "Echo Eagles",
    "Fire Sprinters",
    "Drill Bombers",
    "Rapid Bruisers",
    "Bravo Coyotes",
    "Smoke Reapers",
    "Division Outlaws",
    "Force Raiders",
    "Pack Warriors",
    "Vapor Dragons",
    "Alliance Eagles",
    "Echo Flames",
    "Smoke Nomads",
    "Iron Wolves",
    "Alliance Racers",
    "Echo Rescuers",
    "Blast Raiders",
    "Grip Wolves",
    "Company Hawks",
    "Jet Blazers",
    "Crew Racers",
    "Volt Rockets",
    "Rage Mechanics",
    "Charge Blitz",
    "Fuel Titans",
    "Weld Torchmen",
    "Vapor Flyers",
    "Pulse Cobras",
    "Blast Shockers",
    "Rift Blazers",
    "Volt Warriors",
    "Vector Raiders",
    "Unit Falcons",
    "Rush Flyers",
    "Division Rockets",
    "Fire Responders",
    "Ash Raiders",
    "Steam Firebirds",
    "Rift Racers",
    "Vapor Gunners",
    "Torch Chargers",
    "Brotherhood Strikers",
    "Tempest Rockets",
    "Hose Protectors",
    "Iron Hosemen",
    "Iron Flames",
    "Vapor Falcons",
    "Pack Flyers",
    "Band Hawks",
    "Fuel Runners",
    "Core Sprinters",
    "Ladder Hosemen",
    "Crew Titans",
    "Zone Wolves",
    "Engine Bulls",
    "Gear Rockets",
    "Crew Ironmen",
    "Blaze Cobras",
    "Fuel Falcons",
    "Edge Blitz",
    "Order Cobras",
    "Axis Warriors",
    "Band Racers",
    "Pulse Dragons",
    "Force Firebirds",
    "Vapor Cats",
    "Rescue Nomads",
    "Fuel Flashers",
    "Jet Strikers",
    "Rift Foxes",
    "Shift Gunners",
    "Rescue Outlaws",
    "Vector Flashers",
    "Steam Racers",
    "Zone Trackers",
    "Strike Infernos",
    "Force Bombers",
    "Unit Guardians",
    "Axis Commanders",
    "Ladder Firebirds",
    "Blaze Wolves",
    "Iron Firebirds",
    "Gear Guardians",
    "Front Commanders",
    "Turbo Cobras",
    "Brotherhood Commanders",
    "Core Grinders",
    "Rage Grinders",
    "Smoke Vikings",
    "Delta Ironmen",
    "Weld Flyers",
    "Flash Warriors",
    "Hose Sprinters",
    "Strike Stormers",
    "Pack Blazers",
    "Pack Dragons",
    "Pulse Chargers",
    "Core Runners",
    "Vector Cats",
    "Pulse Rescuers",
    "Rescue Eagles",
    "Flint Protectors",
    "Charge Ironmen",
    "Company Warriors",
    "Zone Falcons",
    "Delta Bruisers",
    "Jet Falcons",
    "Axis Raiders",
    "Order Vultures",
    "Rapid Chargers",
    "Rift Hawks",
    "Bolt Marauders",
    "Grip Eagles",
    "Blast Vikings",
    "Blast Responders",
    "Front Raiders",
    "Torch Rhinos",
    "Shift Flames",
    "Charge Blazers",
    "Thunder Firebirds",
    "Flash Vultures",
    "Core Cobras",
    "Power Runners",
    "Alliance Rockets",
    "Tempest Falcons",
    "Flash Bruisers",
    "Steam Strikers",
    "Flare Foxes",
    "Weld Guardians",
    "Shift Raiders",
    "Iron Commanders",
    "Pulse Rockets",
    "Bolt Chargers",
    "Core Bulls",
    "Rift Raiders",
    "Flash Scorchers",
    "Pack Grinders",
    "Bravo Vikings",
    "Flash Foxes",
    "Inferno Torchmen",
    "Rush Marauders",
    "Rage Strikers",
    "Engine Flames",
    "Inferno Commanders",
    "Bravo Infernos",
    "Jet Eagles",
    "Crew Breakers",
    "Core Chargers",
    "Fire Flames",
    "Echo Warriors",
    "Squad Nomads",
    "Order Rockets",
    "Pulse Breakers",
    "Fire Hounds",
    "Tempest Flames",
    "Vapor Strikers",
    "Rapid Breakers",
    "Pack Falcons",
    "Thunder Mechanics",
    "Division Raiders",
    "Strike Flames",
    "Fuel Jets",
    "Band Rockets",
    "Edge Responders",
    "Ash Trackers",
    "Spark Scorchers",
    "Thunder Flashers",
    "Flint Torchmen",
    "Pulse Torchmen",
    "Ash Warriors",
    "Charge Coyotes",
    "Hose Vultures",
    "Turbo Gunners",
    "Torch Trackers",
    "Pressure Reapers",
    "Gear Shockers",
    "Order Chargers",
    "Surge Stormers",
    "Iron Scorchers",
    "Flare Gunners",
    "Company Titans",
    "Strike Falcons",
    "Delta Rhinos",
    "Power Raiders",
    "Thunder Guardians",
    "Torch Breakers",
    "Inferno Rhinos",
    "Flash Sprinters",
    "Delta Sprinters",
    "Rapid Coyotes",
    "Iron Reapers",
    "Delta Cats",
    "Pulse Blitz",
    "Rush Ironmen",
    "Rush Rhinos",
    "Order Wolves",
    "Grip Hosemen",
    "Vapor Responders",
    "Grip Titans",
    "Unit Coyotes",
    "Grip Reapers",
    "Volt Gunners",
    "Division Strikers",
    "Shift Cats",
    "Turbo Foxes",
    "Force Titans",
    "Weld Rockets",
    "Core Bruisers",
    "Volt Grinders",
    "Flare Infernos",
    "Hose Rockets",
    "Rage Commanders",
    "Surge Cobras",
    "Rage Breakers",
    "Crew Runners",
    "Hose Bruisers",
    "Flint Responders",
    "Ash Responders",
    "Flint Blazers",
    "Flint Runners",
    "Drill Stormers",
    "Power Ironmen",
    "Echo Responders",
    "Torch Marauders",
    "Rift Flyers",
    "Tempest Raiders",
    "Steam Flashers",
    "Flare Vultures",
    "Ladder Flyers",
    "Rush Grinders",
    "Strike Runners",
    "Torch Raiders",
    "Pressure Cats",
    "Drill Marauders",
    "Fire Shockers",
    "Crew Stormers",
    "Pack Stormers",
    "Shift Mechanics",
    "Engine Infernos",
    "Hose Titans",
    "Heat Flyers",
    "Pressure Jets",
    "Core Cats",
    "Vapor Guardians",
    "Volt Titans",
    "Front Nomads",
    "Vector Foxes",
    "Ladder Vultures",
    "Turbo Wolves",
    "Axis Flashers",
    "Smoke Breakers",
    "Jet Rhinos",
    "Alliance Bombers",
    "Pulse Runners",
    "Pack Scorchers",
    "Rescue Vikings",
    "Company Dragons",
    "Pressure Vultures",
    "Flash Raiders",
    "Echo Hounds",
    "Brotherhood Cats",
    "Echo Hosemen",
    "Edge Stormers",
    "Fuel Responders",
    "Flint Flames",
    "Brotherhood Flames",
    "Jet Dragons",
    "Drill Firebirds",
    "Edge Shockers",
    "Turbo Mechanics",
    "Gear Flyers",
    "Flint Rescuers",
    "Rush Infernos",
    "Rage Engines",
    "Tempest Mechanics",
    "Rage Eagles",
    "Jet Raiders",
    "Gear Strikers",
    "Blast Reapers",
    "Zone Blazers",
    "Ash Jets",
    "Edge Rockets",
    "Heat Firebirds",
    "Front Cats",
    "Flint Hounds",
    "Torch Flames",
    "Heat Sprinters",
    "Pressure Mechanics",
    "Order Coyotes",
    "Hose Gunners",
    "Ash Flashers",
    "Engine Rockets",
    "Blaze Nomads",
    "Torch Titans",
    "Engine Cobras",
    "Iron Chargers",
    "Vapor Outlaws",
    "Drill Rescuers",
    "Flint Trackers",
    "Edge Torchmen",
    "Pulse Scorchers",
    "Steel Rescuers",
    "Hose Runners",
    "Grip Warriors",
    "Blaze Blitz",
    "Alliance Outlaws",
    "Rescue Chargers",
    "Rift Vultures",
    "Shift Chargers",
    "Rescue Protectors",
    "Smoke Runners",
    "Flint Flashers",
    "Delta Engines",
    "Bravo Reapers",
    "Blaze Rockets",
    "Fire Jets",
    "Power Marauders",
    "Unit Firebirds",
    "Heat Outlaws",
    "Division Wolves",
    "Unit Jets",
    "Fire Falcons",
    "Edge Jets",
    "Edge Rescuers",
    "Blaze Gunners",
    "Rapid Grinders",
    "Charge Sprinters",
    "Brotherhood Torchmen",
    "Iron Runners",
    "Grit Hawks",
    "Inferno Scorchers",
    "Pulse Outlaws",
    "Unit Eagles",
    "Steel Foxes",
    "Band Blitz",
    "Alliance Dragons",
    "Echo Wolves",
    "Drill Outlaws",
    "Zone Racers",
    "Alliance Responders",
    "Shift Nomads",
    "Smoke Shockers",
    "Vector Flyers",
    "Tempest Bulls",
    "Fire Flashers",
    "Flare Dragons",
    "Pulse Gunners",
    "Vapor Raiders",
    "Band Jets",
    "Zone Gunners",
    "Company Breakers",
    "Tempest Infernos",
    "Drill Engines",
    "Core Foxes",
    "Fire Bruisers",
    "Core Falcons",
    "Gear Mechanics",
    "Brotherhood Rockets",
    "Vapor Flames",
    "Vapor Hounds",
    "Spark Cats",
    "Echo Mechanics",
    "Crew Coyotes",
    "Gear Protectors",
    "Flare Grinders",
    "Blaze Titans",
    "Shift Runners",
    "Front Reapers",
    "Power Scorchers",
    "Alliance Hosemen",
    "Squad Hounds",
    "Rage Scorchers",
    "Order Titans",
    "Steel Runners",
    "Alliance Rhinos",
    "Front Flashers",
    "Rift Rescuers",
    "Flint Shockers",
    "Alliance Warriors",
    "Power Chargers",
    "Brotherhood Trackers",
    "Drill Raiders",
    "Alliance Ironmen",
    "Bolt Guardians",
    "Strike Nomads",
    "Strike Bulls",
    "Crew Bulls",
    "Flint Jets",
    "Power Bulls",
    "Rescue Raiders",
    "Fire Bombers",
    "Edge Protectors",
    "Ash Rescuers",
    "Drill Mechanics",
    "Crew Marauders",
    "Unit Nomads",
    "Steel Raiders",
    "Alliance Vikings",
    "Thunder Engines",
    "Smoke Responders",
    "Grit Coyotes",
    "Inferno Falcons",
    "Gear Bombers",
    "Bravo Stormers",
    "Ash Blitz",
    "Fuel Chargers",
    "Rush Vikings",
    "Brotherhood Vultures",
    "Tempest Rescuers",
    "Fire Breakers",
    "Delta Gunners",
    "Thunder Scorchers",
    "Crew Rhinos",
    "Zone Ironmen",
    "Tempest Commanders",
    "Force Foxes",
    "Ash Outlaws",
    "Delta Bulls",
    "Shift Breakers",
    "Squad Wolves",
    "Flare Hosemen",
    "Bravo Runners",
    "Vapor Engines",
    "Fuel Trackers",
    "Blaze Rescuers",
    "Rapid Mechanics",
    "Blaze Engines",
    "Blaze Vikings",
    "Hose Commanders",
    "Ash Dragons",
    "Pulse Marauders",
    "Inferno Raiders",
    "Zone Titans",
    "Core Nomads",
    "Turbo Guardians",
    "Company Trackers",
    "Front Firebirds",
    "Pulse Raiders",
    "Weld Vultures",
    "Steam Scorchers",
    "Fire Runners",
    "Brotherhood Firebirds",
    "Pack Vikings",
    "Smoke Raiders",
    "Rescue Responders",
    "Axis Hawks",
    "Bravo Hawks",
    "Core Eagles",
    "Band Outlaws",
    "Shift Dragons",
    "Alliance Strikers",
    "Squad Cats",
    "Force Runners",
    "Flare Commanders",
    "Ash Eagles",
    "Rage Flyers",
    "Rift Rockets",
    "Spark Coyotes",
    "Rescue Flames",
    "Bravo Blitz",
    "Heat Chargers",
    "Core Vikings",
    "Volt Foxes",
    "Zone Outlaws",
    "Ash Titans",
    "Inferno Jets",
    "Engine Chargers",
    "Rapid Blitz",
    "Zone Foxes",
    "Flare Outlaws",
    "Edge Rhinos",
    "Rescue Titans",
    "Squad Racers",
    "Gear Vikings",
    "Bolt Dragons",
    "Flint Flyers",
    "Charge Titans",
    "Volt Eagles",
    "Spark Torchmen",
    "Iron Marauders",
    "Delta Infernos",
    "Rescue Bulls",
    "Crew Flames",
    "Bravo Wolves",
    "Vapor Mechanics",
    "Weld Dragons",
    "Rapid Scorchers",
    "Shift Flyers",
    "Company Gunners",
    "Tempest Flashers",
    "Flash Trackers",
    "Rapid Sprinters",
    "Jet Rescuers",
    "Blast Commanders",
    "Gear Racers",
    "Company Commanders",
    "Rage Cobras",
    "Pressure Falcons",
    "Band Foxes",
    "Jet Chargers",
    "Flare Bruisers",
    "Core Raiders",
    "Core Rhinos",
    "Force Blitz",
    "Crew Rescuers",
    "Torch Commanders",
    "Charge Hounds",
    "Steel Protectors",
    "Rapid Guardians",
    "Squad Runners",
    "Steel Stormers",
    "Bolt Vultures",
    "Crew Flashers",
    "Iron Sprinters",
    "Pack Coyotes",
    "Zone Raiders",
    "Strike Rockets",
    "Fire Gunners",
    "Vector Titans",
    "Band Reapers",
    "Ash Bulls",
    "Bravo Falcons",
    "Company Hosemen",
    "Echo Marauders",
    "Weld Wolves",
    "Thunder Breakers",
    "Front Racers",
    "Inferno Foxes",
    "Charge Strikers",
    "Bravo Nomads",
    "Spark Reapers",
    "Front Rescuers",
    "Division Blazers",
    "Vector Blazers",
    "Zone Rescuers",
    "Bravo Outlaws",
    "Rapid Reapers",
    "Pulse Ironmen",
    "Edge Hosemen",
    "Flash Flames",
    "Gear Chargers",
    "Hose Trackers",
    "Order Runners",
    "Engine Rhinos",
    "Bravo Strikers",
    "Zone Chargers",
    "Rapid Rockets",
    "Core Breakers",
    "Pulse Falcons",
    "Weld Flames",
    "Alliance Commanders",
    "Squad Guardians",
    "Surge Rescuers",
    "Squad Trackers",
    "Flint Gunners",
    "Blast Blitz",
    "Ladder Gunners",
    "Rift Runners",
    "Rift Cats",
    "Rush Runners",
    "Delta Hounds",
    "Rift Vikings",
    "Edge Dragons",
    "Fuel Shockers",
    "Strike Flyers",
    "Ladder Responders",
    "Zone Flyers",
    "Rapid Runners",
    "Inferno Guardians",
    "Zone Infernos",
    "Force Warriors",
    "Flare Torchmen",
    "Turbo Warriors",
    "Core Responders",
    "Fuel Mechanics",
    "Fuel Hosemen",
    "Flash Chargers",
    "Smoke Gunners",
    "Alliance Rescuers",
    "Fire Wolves",
    "Charge Flyers",
    "Charge Shockers",
    "Shift Blazers",
    "Echo Titans",
    "Order Marauders",
    "Blaze Grinders",
    "Smoke Trackers",
    "Band Hounds",
    "Engine Falcons",
    "Torch Gunners",
    "Pressure Runners",
    "Surge Wolves",
    "Division Cobras",
    "Pressure Raiders",
    "Turbo Scorchers",
    "Rift Reapers",
    "Heat Rescuers",
    "Fuel Warriors",
    "Heat Guardians",
    "Rescue Scorchers",
    "Echo Infernos",
    "Smoke Eagles",
    "Bravo Bombers",
    "Division Falcons",
    "Power Mechanics",
    "Squad Stormers",
    "Axis Bulls",
    "Grit Racers",
    "Jet Runners",
    "Brotherhood Hounds",
    "Bravo Responders",
    "Echo Flyers",
    "Hose Scorchers",
    "Hose Foxes",
    "Power Blazers",
    "Echo Chargers",
    "Unit Grinders",
    "Iron Responders",
    "Steam Coyotes",
    "Flint Sprinters",
    "Squad Torchmen",
    "Drill Warriors",
    "Rush Commanders",
    "Pressure Eagles",
    "Jet Mechanics",
    "Echo Cats",
    "Zone Cats",
    "Alliance Mechanics",
    "Delta Vultures",
    "Vapor Flashers",
    "Blaze Flames",
    "Iron Raiders",
    "Flare Runners",
    "Company Flames",
    "Hose Flyers",
    "Unit Mechanics",
    "Grit Hounds",
    "Bravo Vultures",
    "Steam Titans",
    "Iron Vultures",
    "Pressure Chargers",
    "Rage Reapers",
    "Strike Rhinos",
    "Rescue Stormers",
    "Axis Flyers",
    "Tempest Chargers",
    "Rift Flashers",
    "Torch Mechanics",
    "Engine Ironmen",
    "Brotherhood Flyers",
    "Rift Marauders",
    "Torch Hosemen",
    "Flint Rockets",
    "Charge Protectors",
    "Edge Runners",
    "Rescue Engines",
    "Unit Bulls",
    "Volt Rhinos",
    "Blaze Hawks",
    "Shift Responders",
    "Volt Responders",
    "Inferno Rescuers",
    "Flint Raiders",
    "Charge Grinders",
    "Band Cobras",
    "Axis Ironmen",
    "Division Bulls",
    "Rapid Ironmen",
    "Rift Bruisers",
    "Spark Breakers",
    "Blaze Chargers",
    "Charge Hosemen",
    "Grit Chargers",
    "Pulse Racers",
    "Bravo Mechanics",
    "Echo Ironmen",
    "Gear Raiders",
    "Unit Ironmen",
    "Grip Runners",
    "Ladder Hawks",
    "Division Nomads",
    "Unit Raiders",
    "Core Blazers",
    "Rush Outlaws",
    "Weld Mechanics",
    "Echo Vultures",
    "Engine Eagles",
    "Fuel Bombers",
    "Edge Cats",
    "Core Hosemen",
    "Zone Bombers",
    "Order Strikers",
    "Alliance Protectors",
    "Hose Torchmen",
    "Turbo Titans",
    "Smoke Hawks",
    "Fire Chargers",
    "Blaze Foxes",
    "Torch Rescuers",
    "Rift Bombers",
    "Flash Bombers",
    "Shift Eagles",
    "Blast Blazers",
    "Brotherhood Hosemen",
    "Spark Nomads",
    "Spark Flashers",
    "Core Commanders",
    "Band Bruisers",
    "Rage Chargers",
    "Rapid Responders",
    "Surge Blazers",
    "Vapor Hosemen",
    "Force Guardians",
    "Thunder Falcons",
    "Grip Guardians",
    "Zone Marauders",
    "Flare Protectors",
    "Rescue Gunners",
    "Ash Chargers",
    "Rescue Rescuers",
    "Steel Blazers",
    "Fuel Hounds",
    "Crew Firebirds",
    "Squad Bruisers",
    "Volt Vikings",
    "Edge Wolves",
    "Ash Infernos",
    "Force Rockets",
    "Edge Gunners",
    "Crew Scorchers",
    "Flint Grinders",
    "Thunder Grinders",
    "Power Rhinos",
    "Brotherhood Rhinos",
    "Band Sprinters",
    "Rescue Vultures",
    "Torch Guardians",
    "Rage Raiders",
    "Ash Torchmen",
    "Pulse Titans",
    "Smoke Rhinos",
    "Core Hawks",
    "Strike Breakers",
    "Squad Eagles",
    "Weld Trackers",
    "Division Torchmen",
    "Rush Bulls",
    "Squad Hosemen",
    "Shift Rescuers",
    "Surge Protectors",
    "Surge Engines",
    "Torch Cats",
    "Bravo Engines",
    "Core Marauders",
    "Drill Runners",
    "Core Infernos",
    "Fuel Rhinos",
    "Surge Commanders",
    "Company Blitz",
    "Bolt Warriors",
    "Heat Grinders",
    "Unit Runners",
    "Power Cats",
    "Rage Marauders",
    "Charge Falcons",
    "Echo Blitz",
    "Vector Marauders",
    "Squad Marauders",
    "Drill Vultures",
    "Company Shockers",
    "Engine Jets",
    "Alliance Runners",
    "Rage Bulls",
    "Spark Rockets",
    "Power Guardians",
    "Weld Strikers",
    "Drill Racers",
    "Squad Mechanics",
    "Flash Blitz",
    "Front Breakers",
    "Pressure Bulls",
    "Charge Runners",
    "Squad Bombers",
    "Echo Grinders",
    "Bolt Shockers",
    "Charge Foxes",
    "Unit Chargers",
    "Steel Chargers",
    "Drill Reapers",
    "Brotherhood Protectors",
    "Ash Reapers",
    "Band Shockers",
    "Fire Reapers",
    "Ash Runners",
    "Rescue Reapers",
    "Rift Dragons",
    "Torch Scorchers",
    "Core Bombers",
    "Fire Ironmen",
    "Alliance Chargers",
    "Pulse Flashers",
    "Band Raiders",
    "Ash Blazers",
    "Core Warriors",
    "Grit Trackers",
    "Pack Hosemen",
    "Flint Vikings",
    "Engine Commanders",
    "Vector Bruisers",
    "Smoke Flashers",
    "Gear Commanders",
    "Pack Bruisers",
    "Squad Cobras",
    "Flare Chargers",
    "Rage Firebirds",
    "Core Outlaws",
    "Alliance Sprinters",
    "Drill Titans",
    "Drill Flyers",
    "Spark Vultures",
    "Power Jets",
    "Volt Raiders",
    "Echo Dragons",
    "Engine Torchmen",
    "Smoke Chargers",
    "Gear Sprinters",
    "Force Bruisers",
    "Charge Gunners",
    "Strike Vikings",
    "Blaze Firebirds",
    "Gear Runners",
    "Company Racers",
    "Surge Gunners",
    "Pulse Hounds",
    "Heat Runners",
    "Ladder Shockers",
    "Pack Infernos",
    "Grit Blazers",
    "Surge Vikings",
    "Surge Reapers",
    "Crew Infernos",
    "Rescue Breakers",
    "Heat Rockets",
    "Brotherhood Foxes",
    "Grit Shockers",
    "Volt Nomads",
    "Axis Blitz",
    "Fuel Raiders",
    "Fuel Commanders",
    "Echo Raiders",
    "Weld Bombers",
    "Rift Hosemen",
    "Iron Rockets",
    "Grit Responders",
    "Hose Dragons",
    "Vector Coyotes",
    "Rage Hosemen",
    "Vector Grinders",
    "Division Flyers",
    "Gear Ironmen",
    "Fire Stormers",
    "Flare Breakers",
    "Rescue Warriors",
    "Strike Titans",
    "Front Torchmen",
    "Vapor Sprinters",
    "Bravo Cobras",
    "Grip Mechanics",
    "Shift Falcons",
    "Force Rescuers",
    "Vapor Chargers",
    "Delta Coyotes",
    "Ash Mechanics",
    "Hose Bombers",
    "Rescue Strikers",
    "Ash Shockers",
    "Pulse Protectors",
    "Zone Runners",
    "Ladder Grinders",
    "Order Firebirds",
    "Tempest Coyotes",
    "Volt Engines",
    "Vector Vikings",
    "Bravo Chargers",
    "Charge Bombers",
    "Jet Protectors",
    "Ash Sprinters",
    "Flare Bombers",
    "Unit Dragons",
    "Thunder Racers",
    "Power Bruisers",
    "Echo Trackers",
    "Grip Bulls",
    "Axis Stormers",
    "Gear Warriors",
    "Rapid Strikers",
    "Echo Blazers",
    "Brotherhood Infernos",
    "Brotherhood Falcons",
    "Tempest Flyers",
    "Vapor Commanders",
    "Inferno Titans",
    "Charge Raiders",
    "Squad Rescuers",
    "Jet Racers",
    "Rage Runners",
    "Steel Firebirds",
    "Blast Sprinters",
    "Grip Ironmen",
    "Blaze Blazers",
    "Volt Wolves",
    "Shift Strikers",
    "Division Ironmen",
    "Pressure Hounds",
    "Alliance Blitz",
    "Flash Engines",
    "Engine Protectors",
    "Charge Chargers",
    "Pulse Strikers",
    "Ladder Commanders",
    "Blaze Marauders",
    "Jet Vultures",
    "Gear Cobras",
    "Brotherhood Nomads",
    "Bravo Commanders",
    "Pulse Grinders",
    "Core Hounds",
    "Charge Bulls",
    "Division Scorchers",
    "Charge Warriors",
    "Pack Rescuers",
    "Pack Flames",
    "Pressure Breakers",
    "Flash Torchmen",
    "Flare Rescuers",
    "Edge Hounds",
    "Pack Cobras",
    "Front Ironmen",
    "Rift Scorchers",
    "Grit Dragons",
    "Vapor Cobras",
    "Zone Torchmen",
    "Fire Hosemen",
    "Tempest Bombers",
    "Crew Gunners",
    "Vector Ironmen",
    "Hose Grinders",
    "Turbo Vultures",
    "Unit Hounds",
    "Pack Foxes",
    "Blast Trackers",
    "Division Firebirds",
    "Band Chargers",
    "Torch Cobras",
    "Pulse Hosemen",
    "Company Torchmen",
    "Fuel Vikings",
    "Bolt Scorchers",
    "Vector Guardians",
    "Grip Cats",
    "Bravo Shockers",
    "Axis Vikings",
    "Thunder Flames",
    "Order Racers",
    "Torch Sprinters",
    "Jet Nomads",
    "Company Flashers",
    "Gear Falcons",
    "Brotherhood Runners",
    "Order Jets",
    "Heat Racers",
    "Echo Vikings",
    "Engine Trackers",
    "Company Infernos",
    "Smoke Foxes",
    "Iron Engines",
    "Grit Runners",
    "Strike Dragons",
    "Weld Gunners",
    "Core Racers",
    "Hose Nomads",
    "Vapor Marauders",
    "Zone Hawks",
    "Rapid Commanders",
    "Steel Marauders",
    "Grip Foxes",
    "Axis Infernos",
    "Inferno Racers",
    "Echo Racers",
    "Rift Eagles",
    "Grip Falcons",
    "Core Titans",
    "Pressure Grinders",
    "Pressure Titans",
    "Iron Protectors",
    "Fuel Bruisers",
    "Iron Blitz",
    "Flare Nomads",
    "Grip Jets",
    "Brotherhood Bulls",
    "Ladder Flashers",
    "Grit Reapers",
    "Axis Marauders",
    "Engine Titans",
    "Grit Gunners",
    "Flash Marauders",
    "Turbo Bombers",
    "Rage Infernos",
    "Brotherhood Blazers",
    "Unit Rescuers",
    "Blaze Stormers",
    "Inferno Protectors",
    "Order Rescuers",
    "Flare Wolves",
    "Brotherhood Titans",
    "Echo Protectors",
    "Pack Cats",
    "Tempest Scorchers",
    "Company Runners",
    "Steam Ironmen",
    "Strike Ironmen",
    "Delta Torchmen",
    "Squad Strikers",
    "Unit Cobras",
    "Surge Chargers",
    "Thunder Stormers",
    "Grit Vikings",
    "Hose Hosemen",
    "Grip Bombers",
    "Pulse Bombers",
    "Pack Shockers",
    "Blast Runners",
    "Alliance Grinders",
    "Zone Guardians",
    "Blaze Coyotes",
    "Flash Responders",
    "Crew Vultures",
    "Vector Eagles",
    "Force Reapers",
    "Unit Infernos",
    "Front Sprinters",
    "Rescue Marauders",
    "Force Responders",
    "Delta Falcons",
    "Flint Blitz",
    "Bravo Gunners",
    "Power Racers",
    "Volt Falcons",
    "Tempest Wolves",
    "Heat Engines",
    "Zone Vultures",
    "Front Cobras",
    "Force Shockers",
    "Turbo Stormers",
    "Surge Infernos",
    "Drill Strikers",
    "Charge Vultures",
    "Rescue Falcons",
    "Flare Warriors",
    "Flare Flames",
    "Smoke Jets",
    "Bravo Sprinters",
    "Flash Hawks",
    "Order Blitz",
    "Steam Rhinos",
    "Volt Scorchers",
    "Force Engines",
    "Flare Titans",
    "Smoke Flyers",
    "Unit Breakers",
    "Bolt Eagles",
    "Ladder Chargers",
    "Company Guardians",
    "Pressure Engines",
    "Vector Firebirds",
    "Division Runners",
    "Pressure Racers",
    "Pulse Vultures",
    "Rescue Hawks",
    "Inferno Ironmen",
    "Steam Reapers",
    "Gear Gunners",
    "Surge Eagles",
    "Force Scorchers",
    "Weld Runners",
    "Ladder Engines",
    "Flash Stormers",
    "Brotherhood Marauders",
    "Tempest Runners",
    "Force Chargers",
    "Grit Nomads",
    "Company Chargers",
    "Iron Cobras",
    "Echo Sprinters",
    "Unit Responders",
    "Brotherhood Racers",
    "Flash Strikers",
    "Bolt Cats",
    "Rescue Sprinters",
    "Weld Coyotes",
    "Order Guardians",
    "Rage Torchmen",
    "Weld Blazers",
    "Grit Jets",
    "Engine Outlaws",
    "Shift Reapers",
    "Thunder Hounds",
    "Delta Cobras",
    "Squad Dragons",
    "Spark Titans",
    "Charge Bruisers",
    "Delta Rescuers",
    "Edge Grinders",
    "Crew Outlaws",
    "Vector Dragons",
    "Company Stormers",
    "Unit Hosemen",
    "Iron Shockers",
    "Power Shockers",
    "Front Strikers",
    "Rush Blazers",
    "Spark Wolves",
    "Volt Sprinters",
    "Iron Breakers",
    "Drill Foxes",
    "Rapid Hosemen",
    "Delta Firebirds",
    "Jet Firebirds",
    "Pressure Dragons",
    "Strike Responders",
    "Drill Breakers",
    "Tempest Sprinters",
    "Fuel Stormers",
    "Order Flames",
    "Drill Gunners",
    "Axis Cats",
    "Smoke Bulls",
    "Alliance Bruisers",
    "Force Jets",
    "Grip Vultures",
    "Delta Stormers",
    "Spark Raiders",
    "Surge Sprinters",
    "Front Outlaws",
    "Steam Wolves",
    "Thunder Rescuers",
    "Edge Warriors",
    "Bolt Commanders",
    "Thunder Strikers",
    "Rage Sprinters",
    "Gear Reapers",
    "Grip Sprinters",
    "Engine Runners",
    "Grip Blitz",
    "Ladder Raiders",
    "Gear Eagles",
    "Rapid Raiders",
    "Spark Guardians",
    "Drill Infernos",
    "Echo Runners",
    "Steel Coyotes",
    "Bolt Titans",
    "Steam Vultures",
    "Rift Cobras",
    "Volt Stormers",
    "Blast Nomads",
    "Edge Infernos",
    "Torch Vultures",
    "Rush Bombers",
    "Axis Hosemen",
    "Drill Ironmen",
    "Engine Hounds",
    "Fire Raiders",
    "Spark Jets",
    "Fuel Infernos",
    "Fire Foxes",
    "Weld Raiders",
    "Rush Flames",
    "Flint Chargers",
    "Jet Flames",
    "Echo Shockers",
    "Flint Rhinos",
    "Smoke Blazers",
    "Rift Commanders",
    "Vector Nomads",
    "Ladder Blazers",
    "Bolt Reapers",
    "Turbo Firebirds",
    "Volt Hawks",
    "Inferno Flames",
    "Rage Warriors",
    "Heat Shockers",
    "Drill Shockers",
    "Rush Stormers",
    "Rush Flashers",
    "Squad Flashers",
    "Vapor Titans",
    "Blast Stormers",
    "Grip Raiders",
    "Bravo Guardians",
    "Echo Hawks",
    "Echo Coyotes",
    "Brotherhood Breakers",
    "Gear Firebirds",
    "Core Rockets",
    "Weld Cats",
    "Pack Torchmen",
    "Unit Vikings",
    "Ash Cobras",
    "Charge Dragons",
    "Strike Warriors",
    "Rapid Flames",
    "Order Eagles",
    "Charge Rockets",
    "Band Hosemen",
    "Engine Cats",
    "Strike Vultures",
    "Crew Chargers",
    "Flint Breakers",
    "Volt Chargers",
    "Bravo Rhinos",
    "Vector Infernos",
    "Steam Hosemen",
    "Order Falcons",
    "Power Flames",
    "Surge Raiders",
    "Vector Wolves",
    "Axis Runners",
    "Shift Shockers",
    "Smoke Commanders",
    "Blast Engines",
    "Flare Cats",
    "Heat Dragons",
    "Vapor Shockers",
    "Smoke Hosemen",
    "Inferno Coyotes",
    "Edge Marauders",
    "Pressure Flames",
    "Echo Nomads",
    "Power Sprinters",
    "Jet Responders",
    "Rift Responders",
    "Pulse Responders",
    "Steel Sprinters",
    "Ash Commanders",
    "Core Mechanics",
    "Thunder Wolves",
    "Front Chargers",
    "Flare Cobras",
    "Jet Cobras",
    "Blaze Torchmen",
    "Steel Reapers",
    "Zone Hounds",
    "Thunder Blitz",
    "Delta Trackers",
    "Thunder Raiders",
    "Shift Foxes",
    "Engine Rescuers",
    "Pulse Flames",
    "Pulse Engines",
    "Echo Bulls",
    "Flash Bulls",
    "Brotherhood Reapers",
    "Core Guardians",
    "Inferno Chargers",
    "Ash Grinders",
    "Surge Blitz",
    "Crew Cobras",
    "Band Torchmen",
    "Tempest Eagles",
    "Unit Racers",
    "Steel Eagles",
    "Pulse Guardians",
    "Band Bombers",
    "Pressure Guardians",
    "Strike Cobras",
    "Order Hounds",
    "Vapor Racers",
    "Weld Sprinters",
    "Rage Shockers",
    "Rapid Vultures",
    "Order Bulls",
    "Power Dragons",
    "Band Blazers",
    "Delta Flyers",
    "Shift Ironmen",
    "Brotherhood Bombers",
    "Company Raiders",
    "Flint Infernos",
    "Thunder Commanders",
    "Core Shockers",
    "Heat Gunners",
    "Rapid Flyers",
    "Blaze Bruisers",
    "Turbo Coyotes",
    "Pulse Foxes",
    "Rapid Falcons",
    "Drill Hawks",
    "Grit Cats",
    "Blast Marauders",
    "Inferno Vikings",
    "Axis Chargers",
    "Pressure Infernos",
    "Thunder Titans",
    "Axis Bruisers",
    "Echo Rhinos",
    "Vector Runners",
    "Unit Rhinos",
    "Torch Ironmen",
    "Crew Vikings",
    "Strike Scorchers",
    "Gear Cats",
    "Smoke Infernos",
    "Front Responders",
    "Squad Raiders",
    "Company Coyotes",
    "Brotherhood Outlaws",
    "Ladder Strikers",
    "Surge Foxes",
    "Force Commanders",
    "Volt Strikers",
    "Fuel Scorchers",
    "Alliance Stormers",
    "Grit Engines",
    "Band Firebirds",
    "Delta Marauders",
    "Shift Infernos",
    "Flare Falcons",
    "Power Trackers",
    "Turbo Ironmen",
    "Rush Guardians",
    "Pulse Flyers",
    "Flash Vikings",
    "Alliance Vultures",
    "Edge Racers",
    "Squad Responders",
    "Bravo Cats",
    "Blast Warriors",
    "Iron Grinders",
    "Blast Chargers",
    "Rescue Wolves",
    "Grit Titans",
    "Front Hounds",
    "Unit Rockets",
    "Rescue Mechanics",
    "Crew Hounds",
    "Fuel Vultures",
    "Fire Cobras",
    "Weld Hosemen",
    "Ash Breakers",
    "Crew Flyers",
    "Smoke Blitz",
    "Smoke Racers",
    "Heat Cobras",
    "Ladder Flames",
    "Surge Runners",
    "Hose Mechanics",
    "Order Raiders",
    "Inferno Marauders",
    "Axis Mechanics",
    "Blaze Hounds",
    "Inferno Flyers",
    "Core Strikers",
    "Charge Outlaws",
    "Front Flames",
    "Power Torchmen",
    "Jet Marauders",
    "Strike Hosemen",
    "Rage Foxes",
    "Rapid Blazers",
    "Charge Torchmen",
    "Rush Hosemen",
    "Rift Breakers",
    "Echo Commanders",
    "Smoke Rescuers",
    "Tempest Strikers",
    "Weld Rhinos",
    "Ash Flames",
    "Division Chargers",
    "Steel Racers",
    "Echo Engines",
    "Pressure Foxes",
    "Division Vultures",
    "Bravo Bulls",
    "Fuel Guardians",
    "Tempest Hosemen",
    "Steam Blazers",
    "Tempest Ironmen",
    "Rescue Shockers",
    "Unit Strikers",
    "Turbo Reapers",
    "Jet Cats",
    "Tempest Jets",
    "Ladder Infernos",
    "Alliance Cobras",
    "Surge Jets",
    "Edge Mechanics",
    "Rapid Infernos",
    "Flash Racers",
    "Core Stormers",
    "Grit Bombers",
    "Shift Commanders",
    "Jet Hounds",
    "Division Hawks",
    "Strike Protectors",
    "Rage Gunners",
    "Rage Jets",
    "Delta Hosemen",
    "Delta Runners",
    "Rage Hawks",
    "Rage Cats",
    "Turbo Protectors",
    "Heat Nomads",
    "Brotherhood Vikings",
    "Order Vikings",
    "Strike Commanders",
    "Grit Blitz",
    "Blaze Rhinos",
    "Delta Blazers",
    "Blaze Dragons",
    "Vector Responders",
    "Spark Chargers",
    "Flint Dragons",
    "Blaze Scorchers",
    "Drill Scorchers",
    "Power Cobras",
    "Surge Nomads",
    "Front Engines",
    "Steam Trackers",
    "Delta Protectors",
    "Bolt Breakers",
    "Rescue Racers",
    "Inferno Bruisers",
    "Fire Commanders",
    "Strike Wolves",
    "Band Strikers",
    "Pack Reapers",
    "Pressure Flyers",
    "Flash Wolves",
    "Force Blazers",
    "Squad Foxes",
    "Delta Flames",
    "Heat Titans",
    "Ladder Rockets",
    "Blaze Ironmen",
    "Rescue Blitz",
    "Thunder Protectors",
    "Ash Scorchers",
    "Blaze Vultures",
    "Iron Eagles",
    "Flint Strikers",
    "Rush Racers",
    "Pressure Gunners",
    "Steam Mechanics",
    "Zone Stormers",
    "Blast Infernos",
    "Heat Infernos",
    "Ash Marauders",
    "Company Scorchers",
    "Squad Infernos",
    "Squad Grinders",
    "Blast Rhinos",
    "Alliance Blazers",
    "Echo Foxes",
    "Surge Scorchers",
    "Flint Coyotes",
    "Squad Jets",
    "Pack Runners",
    "Company Sprinters",
    "Rage Titans",
    "Jet Torchmen",
    "Rush Foxes",
    "Hose Blitz",
    "Heat Flames",
    "Grip Chargers",
    "Gear Bruisers",
    "Power Foxes",
    "Hose Falcons",
    "Pack Bombers",
    "Blaze Mechanics",
    "Blast Ironmen",
    "Brotherhood Bruisers",
    "Steam Grinders",
    "Ash Protectors",
    "Flint Bulls",
    "Gear Hosemen",
    "Grit Flames",
    "Steam Hounds",
    "Charge Firebirds",
    "Engine Vultures",
    "Rapid Foxes",
    "Power Outlaws",
    "Blaze Hosemen",
    "Axis Flames",
    "Steam Falcons",
    "Delta Mechanics",
    "Rapid Hounds",
    "Bolt Responders",
    "Edge Chargers",
    "Steel Wolves",
    "Delta Outlaws",
    "Hose Cats",
    "Vapor Wolves",
    "Strike Jets",
    "Axis Protectors",
    "Vector Stormers",
    "Drill Rhinos",
    "Ladder Falcons",
    "Engine Gunners",
    "Steel Flyers",
    "Zone Eagles",
    "Squad Commanders",
    "Pressure Commanders",
    "Axis Bombers",
    "Crew Warriors",
    "Drill Cobras",
    "Strike Engines",
    "Volt Cobras",
    "Fuel Cats",
    "Order Gunners",
    "Bolt Runners",
    "Jet Engines",
    "Ladder Vikings",
    "Grit Outlaws",
    "Division Racers",
    "Pulse Bulls",
    "Squad Engines",
    "Zone Commanders",
    "Front Runners",
    "Delta Responders",
    "Rush Hawks",
    "Fire Titans",
    "Unit Flames",
    "Steel Vultures",
    "Steel Breakers",
    "Thunder Responders",
    "Pressure Warriors",
    "Flash Gunners",
    "Ash Coyotes",
    "Flash Nomads",
    "Charge Scorchers",
    "Company Bruisers",
    "Tempest Breakers",
    "Division Warriors",
    "Delta Flashers",
    "Gear Outlaws",
    "Heat Foxes",
    "Axis Blazers",
    "Bravo Grinders",
    "Bravo Flashers",
    "Zone Responders",
    "Heat Bombers",
    "Vapor Infernos",
    "Thunder Reapers",
    "Pack Engines",
    "Division Vikings",
    "Turbo Jets",
    "Axis Titans",
    "Rush Shockers",
    "Bolt Firebirds",
    "Power Strikers",
    "Smoke Stormers",
    "Turbo Runners",
    "Pressure Stormers",
    "Order Sprinters",
    "Power Hosemen",
    "Axis Torchmen",
    "Pulse Rhinos",
    "Pressure Rhinos",
    "Drill Protectors",
    "Bolt Hawks",
    "Axis Strikers",
    "Gear Grinders",
    "Charge Infernos",
    "Core Wolves",
    "Echo Scorchers",
    "Torch Shockers",
    "Pulse Mechanics",
    "Bravo Foxes",
    "Zone Scorchers",
    "Tempest Hawks",
    "Strike Blazers",
    "Force Dragons",
    "Flint Wolves",
    "Core Protectors",
    "Blaze Raiders",
    "Volt Vultures",
    "Blast Coyotes",
    "Core Dragons",
    "Smoke Dragons",
    "Alliance Nomads",
    "Steam Raiders",
    "Charge Rescuers",
    "Alliance Falcons",
    "Steel Guardians",
    "Charge Commanders",
    "Engine Engines",
    "Rapid Cats",
    "Delta Guardians",
    "Fire Mechanics",
    "Torch Runners",
    "Pulse Trackers",
    "Edge Scorchers",
    "Hose Chargers",
    "Strike Chargers",
    "Weld Engines",
    "Rescue Hounds",
    "Spark Bruisers",
    "Rush Trackers",
    "Edge Flashers",
    "Pack Eagles",
    "Delta Jets",
    "Band Eagles",
    "Unit Protectors",
    "Front Gunners",
    "Flare Guardians",
    "Spark Strikers",
    "Company Jets",
    "Bravo Trackers",
    "Bolt Strikers",
    "Crew Falcons",
    "Fire Bulls",
    "Crew Shockers",
    "Alliance Flames",
    "Turbo Falcons",
    "Alliance Wolves",
    "Unit Torchmen",
    "Core Torchmen",
    "Axis Breakers",
    "Crew Hawks",
    "Steam Flyers",
    "Ladder Titans",
    "Charge Cobras",
    "Axis Coyotes",
    "Force Strikers",
    "Company Blazers",
    "Hose Reapers",
    "Spark Bombers",
    "Band Infernos",
    "Echo Bombers",
    "Rift Nomads",
    "Vapor Stormers",
    "Drill Bruisers",
    "Rift Blitz",
    "Pressure Trackers",
    "Echo Torchmen",
    "Delta Warriors",
    "Drill Blitz",
    "Fuel Flames",
    "Unit Wolves",
    "Bolt Flyers",
    "Order Infernos",
    "Blast Vultures",
    "Crew Bombers",
    "Gear Bulls",
    "Rift Strikers",
    "Crew Responders",
    "Gear Foxes",
    "Steam Nomads",
    "Division Sprinters",
    "Weld Jets",
    "Surge Firebirds",
    "Vapor Warriors",
    "Fire Coyotes",
    "Unit Titans",
    "Fuel Protectors",
    "Flare Hawks",
    "Rush Raiders",
    "Brotherhood Warriors",
    "Bravo Titans",
    "Drill Rockets",
    "Steel Vikings",
    "Delta Chargers",
    "Division Dragons",
    "Vapor Firebirds",
    "Rescue Bruisers",
    "Order Rhinos",
    "Weld Scorchers",
    "Spark Blazers",
    "Fuel Blazers",
    "Rage Flames",
    "Drill Sprinters",
    "Division Reapers",
    "Blaze Protectors",
    "Band Scorchers",
    "Torch Foxes",
    "Shift Vikings",
    "Echo Cobras",
    "Shift Hosemen",
    "Weld Warriors",
    "Rage Blitz",
    "Edge Raiders",
    "Charge Wolves",
    "Grip Trackers",
    "Steel Mechanics",
    "Rescue Trackers",
    "Rescue Blazers",
    "Echo Firebirds",
    "Tempest Marauders",
    "Division Bruisers",
    "Front Jets",
    "Turbo Hawks"
];   
}